[package]
name = "hashers_proc_macro"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "proc-macro for hash_utils"
repository = "https://github.com/mkaraki/hash_utils.git"

[lib]
proc-macro = true
[dependencies]
quote = "1.0.38"
syn = "2.0.98"
convert_case = "0.7.1"